kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-server
  namespace: default
  uid: 6f771ef7-b649-47e2-9811-94ca715766ba
  resourceVersion: '1814'
  generation: 2
  creationTimestamp: '2021-02-25T21:15:11Z'
  labels:
    app: web-server
  annotations:
    deployment.kubernetes.io/revision: '1'
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: apps/v1
      time: '2021-02-25T21:15:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"devopstestweb"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-02-28T17:25:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-server
    spec:
      containers:
        - name: devopstestweb
          image: 'gfengster/devopstestweb:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-02-25T21:15:36Z'
      lastTransitionTime: '2021-02-25T21:15:11Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "web-server-76478c5ff7" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-02-28T17:25:34Z'
      lastTransitionTime: '2021-02-28T17:25:34Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
