version: "3"
services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: NginxDockerfile
    
    ports:
      - "80:80"

    networks:
        frontend_net:
            ipv4_address: 172.20.0.118
        backend_net:


  web1:
    container_name: devops-test_web_1
    build: 
      context: .
      dockerfile: Dockerfile
      
    networks:
        backend_net:
      
  web2:
    container_name: devops-test_web_2
    build: 
      context: .
      dockerfile: Dockerfile
     
    networks:
        backend_net:
            
       
networks:
    backend_net:
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/16
                
    frontend_net:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16         
