name: GFeng CI/CD

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code 
        uses: actions/checkout@v2

      - name: Install NPM
        uses: c-hive/gha-npm-cache@v1

      - name: Run test
        run: npm test

