name: GFeng CI/CD

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Build_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code 
        uses: actions/checkout@v2

      - name: Start cluster
        run: docker-compose up --build -d
      
      - name: Start up cluster
        run: sleep 20
        
      - name: First time curl the cluster 
        run: curl -s http://localhost && echo "" && curl -s http://localhost 
        
      - name: Second time curl the cluster
        run: curl -s http://localhost && echo "" && curl -s http://localhost

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Rename docker web server image 
        run: docker tag devops-test_web1:latest gfengster/devops-test_web:latest
        
      - name: Publish docker web server image
        run: docker push gfengster/devops-test_web:latest
     
      - name: Rename docker load balancer image 
        run: docker tag devops-test_gateway:latest gfengster/devops-test_gateway:latest
        
      - name: Publish docker load balancer image
        run: docker push gfengster/devops-test_gateway:latest
        

